version: "3.8"

services:
  postgres:
    container_name: "exams-db-container"
    image: "postgres:latest"
    platform: linux/amd64
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "gitpass2016"
      POSTGRES_DB: "exams_db"
    volumes:
      - postgres-data:/var/lib/postgresql/data


volumes:
  cache:
  postgres-data: